### ISSUE TITLE
[Enhancement] Port to Native Debug and register view

### ISSUE THREAD

**Issue by jjchico** [newtonsart/vscode-assembly#1]
Hi! This is really useful thanks. It seems GDB Debug is no longer maintained but it seems it is possible to port your configuration to use Native Debug.
Another unrelated question is that I cannot find a way to have the registers displayed in the VARIABLES window as shown in your screenshot. Any clue on that would be really helpful.
Thanks again.

**Comment by newtonsart** [comment]
Hello, thank you very much for taking time and reviewing this repository. The registers displayed in the VARIABLES window are a feature of GDB Debug, I've talked with the developer of GDB Debug and you are right, it's no longer maintained, but I've chosen that extension because of the regiters window.
And again, thank you very much for reviewing and trying my code.

**Comment by jjchico** [comment]
Hi!
It is a pity GDB Debug is no longer maintained since I think there is not any other GDB interface that provides a register view, which is really useful for assembly debugging and teaching.
Thanks for the detailed information.
Regards.
